version: "3.3"

services:
    nginx:
        build: ./requirements/nginx
        image: nginx
        env_file:
            - .env
        container_name: nginx_container
        restart: always
        ports:
            - "443:443"
        volumes:
            - wordpress_volume:/var/www/html
        networks:
            - network
        depends_on:
            - wordpress

    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        env_file:
            - .env
        container_name: mariadb_container
        restart: always
        volumes:
            - mariadb_volume:/var/lib/mysql
        networks:
            - network

    wordpress:
        image: wordpress
        env_file:
            - .env
        container_name: wordpress_container
        restart: always
        build: ./requirements/wordpress
        volumes:
            - wordpress_volume:/var/www/html
        networks:
            - network
        depends_on:
            - mariadb
            - redis
    
    # bonus
    redis:
        image: redis:latest
        build: ./requirements/bonus/redis
        container_name: redis_container
        ports:
            - "6379:6379"
        volumes:
            - wordpress_volume:/var/www/wordpress
        networks:
            - network
        env_file: .env
        restart: always

    adminer:
        image: adminer:latest
        container_name: adminer_container
        build: ./requirements/bonus/adminer
        volumes:
            - wordpress_volume:/var/www/wordpress
        networks:
            - network
        depends_on:
            - mariadb
        expose:
            - "9000"

    ftp:
        image: ftp:latest
        container_name: ftp_container
        build: ./requirements/bonus/ftp
        volumes:
            - wordpress_volume:/ftp
        ports:
            - "21:21"
            - "20:20"
            - "21000-21000:21000-21000"
        networks:
            - network
        depends_on:
            - wordpress
        env_file: .env

    site:
        image: site:latest
        restart: always
        container_name: site_container
        build: ./requirements/bonus/site
        networks:
            - network

    docker-container-stats:
        build: ./requirements/bonus/container_statistics
        container_name: docker-container-stats
        ports:
            - "8080:8080"
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/home/docker/storage/stats/db:/opt/docker-stats/db'
        restart: always

volumes:
    wordpress_volume:
        driver: local
        driver_opts:
            device: /home/login/data/wordpress
            o: bind
            type: none
    mariadb_volume:
        driver: local
        driver_opts:
            device: /home/login/data/mariadb
            o: bind
            type: none

networks:
    network:
        driver: bridge
